# ---------------------------------------------------------------------------- #
#                                                                              #
#                    S t e p M e n u . p r o p e r t i e s                     #
#                                                                              #
# ---------------------------------------------------------------------------- #

# This file gathers resources to be injected in the StepMenu class
#
# This is the generic (english) version

LOAD.text           = Load
LOAD.description    = Get the sheet gray picture

BINARY.text         = Binary
BINARY.description  = Binarize the sheet gray picture

SCALE.text          = Scale
SCALE.description   = Compute sheet line thickness, interline, beam thickness

GRID.text           = Grid
GRID.description    = Retrieve staff lines, barlines, systems & parts

HEADERS.text        = Headers
HEADERS.description = Retrieve Clef-Key-Time systems headers

STEM_SEEDS.text         = Stem Seeds
STEM_SEEDS.description  = Retrieve stem thickness & seeds for stems

BEAMS.text          = Beams
BEAMS.description   = Retrieve beams

LEDGERS.text        = Ledgers
LEDGERS.description = Retrieve ledgers

HEADS.text          = Heads
HEADS.description   = Retrieve note heads

STEMS.text          = Stems
STEMS.description   = Retrieve stems connected to heads & beams

REDUCTION.text          = Reduction
REDUCTION.description   = Reduce conflicts in heads, stems & beams

CUE_BEAMS.text          = Cue Beams
CUE_BEAMS.description   = Retrieve cue beams

TEXTS.text          = Texts
TEXTS.description   = Call OCR on textual items

MEASURES.text       = Measures
MEASURES.description= Retrieve raw measures from groups of barlines

CHORDS.text         = Chords
CHORDS.description  = Gather notes heads into chords

CURVES.text         = Curves
CURVES.description  = Retrieve slurs, wedges & endings

SYMBOLS.text        = Symbols
SYMBOLS.description = Retrieve fixed-shape symbols

LINKS.text          = Links
LINKS.description   = Link and reduce symbols

RHYTHMS.text        = Rhythms
RHYTHMS.description = Handle rhythms within measures

PAGE.text           = Page
PAGE.description    = Connect systems within page
