# ---------------------------------------------------------------------------- #
#                                                                              #
#                     M a i n G u i . p r o p e r t i e s                      #
#                                                                              #
# ---------------------------------------------------------------------------- #

# This file gathers resources to be injected in the MainGui class
#
# This is the generic version

# Standard application resources
#-------------------------------

# (Application.name) A short name, typically just a few words
Application.name = NoteLite

# Application.id is used to store session data across runs
Application.id = notelite

# Application.vendorId is used to store session data across runs
Application.vendorId = NoteLiteOrg
Application.icon = icon-24.png

Application.lookAndFeel = com.formdev.flatlaf.themes.FlatMacLightLaf
#Application.lookAndFeel = com.formdev.flatlaf.themes.FlatMacDarkLaf
#Application.lookAndFeel = com.formdev.flatlaf.FlatLightLaf
#Application.lookAndFeel = com.formdev.flatlaf.FlatDarkLaf
#Application.lookAndFeel = com.jgoodies.looks.plastic.Plastic3DLookAndFeel

# Application.vendor is only displayed in About box
Application.vendor = NoteLite
Application.title = NoteLite Music Scanner
Application.homepage = http://www.notelite.example.com
Application.description = Optical Music Recognition
Application.projectpage = https://github.com/ORG/notelite

# Reference to selected Crystal icons
smallIcons = /crystal/22x22
largeIcons = /crystal/32x32
