# ---------------------------------------------------------------------------- #
#                                                                              #
#                   U n i t M o d e l . p r o p e r t i e s                    #
#                                                                              #
# ---------------------------------------------------------------------------- #

# This file gathers resources to be injected in the UnitModel class
#
# This is the generic (english) version

TREE.header     = Unit
MODIF.header    = Modif
TYPE.header     = Type
UNIT.header     = Unit
PIXEL.header    = Pixels
VALUE.header    = Value
DESC.header     = Description
